FROM mcr.microsoft.com/mssql/server:2022-latest

# Variables de entorno
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer

# Exponer puerto
EXPOSE 1433

# SQL Server se inicia automáticamente con el entrypoint por defecto